### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by megastep**
Enjoy!

### CODE REVIEW

**Comment by aure** [comment]
@megastep @analogcode What's the status of this pull request?

**Comment by megastep** [comment]
It's an automated PR from CrowdIn. I merge it manually whenever new translations are completed. We should leave it open though because they'll just create a new one if we close it.

**Comment by aure** [comment]
@megastep Thanks for the clarification.

**Comment by megastep** [comment]
Great, that's just going to trigger a new one being open ;)

**Pull request merged**
